-keep class com.sun.jna.** { *; }
-keep class uk.co.caprica.vlcj.** { *; }
-keep class org.sqlite.** { *; }
-keep class org.jaudiotagger.tag.** { *; }
-keep class kotlinx.coroutines.swing.SwingDispatcherFactory