-keep class com.sun.jna.** { *; }
-keep class * implements com.sun.jna.** { *; }
-keep class uk.co.caprica.vlcj.** { *; }
-keep class * implements uk.co.caprica.vlcj.** { *; }
-keep class org.sqlite.** { *; }
-keep class kotlinx.coroutines.swing.SwingDispatcherFactory